openapi: 3.0.0
info:
 title: Schedule Attachment Analysis API
 description: Schedule Attachment Analysis Use Case Specification
 version: 1.0.0

servers:
 - ServiceNow
   description: send case needing Sandbox Analysis to Sandbox
 - Sandbox
   description: send updated case to OpenC2

paths:
   post:
     summary: ServiceNow sends a PhishCase to analyze.
     security:
       - BasicAuth: []
     requestBody:
       description: PhishCase is sent to Sandbox
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/PhishCase'
     responses:
       $ref: #/components/responses/200OK