openapi: 3.0.0
info:
 title: Sandbox Analysis Result API
 description: Sandbox Analysis result Use Case Specification
 version: 1.0.0

servers:
 - Sandbox
   description: send analyzed PhishCase to OpenC2
 - OpenC2
   description: receive analyzed case from Sandbox

paths:
   post:
     summary: Sandbox sends analysis result.
     security:
       - BasicAuth: []
     requestBody:
       description: PhishCase is sent to OpenC2
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/PhishCase'
     responses:
       '200':    # status code
         description: OK. sends confirmation message as a string
         content:
           application/json:
             schema:
               type: string