openapi: 3.0.0
info:
 title: Proofpoint Signal API
 description: Proofpoint Signal Use Case Specification
 version: 1.0.0

servers:
 - Proofpoint
   description: Sends a PhishCase object to OpenC2
 - OpenC2
   description: Receives PhishCase from Proofpoint

paths:
   post:
     summary: Proofpoint sends PhishCase to OpenC2.
     security:
       - BasicAuth: []
     requestBody:
       description: Signal is sent to OpenC2
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/PhishCase'
     responses:
       $ref: #/components/responses/200OK
